name: tests

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.txt'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.txt'

jobs:
  test-cmdline:
    runs-on: ${{ matrix.os }}

    #runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: [3.7, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run the test
      run: |
        cd sample_project
        ./test_pkg_as_cmdline.sh
        [ $(< ~/output.txt) == "hi!" ] || exit 1

  test-module:
      runs-on: ${{ matrix.os }}

      #runs-on: ubuntu-latest
      timeout-minutes: 5
      strategy:
        matrix:
          os: [macos-latest, ubuntu-latest]
          python-version: [3.7, 3.9]

      steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run the test
        run: |
          cd sample_project
          ./test_pkg_as_module.sh
          [ $(< ~/output.txt) == "hi!" ] || exit 1